### ISSUE TITLE
TypeError encountered during initial test

### ISSUE THREAD

**Issue by famugong** [whiteblackitty/SQLCipher-Password-Cracker-OpenCL#5]
During the initial testing cracking the generated DB, I encountered following message after some 20 cycles. For a DB with default password, this message appears immediately. So I presume it's an issue with the final result.

Traceback (most recent call last):
  File "Run.py", line 202, in <module>
    main(sys.argv)
  File "Run.py", line 177, in main
    if(tryDecryptSQLiteDB(result)==True): # validation
  File "Run.py", line 41, in tryDecryptSQLiteDB
    passphrase+=chr(pword)
TypeError: only integer scalar arrays can be converted to a scalar index

**Comment by whiteblackitty** [comment]
This problem seems to be an issue of python version. The code works for python 3.7, and other version is not supported. To make the code work for other version of python, please use the search engine and python document to seek for help. You can paste your solution here so that other developers will benefit from it.

**Comment by jasonhancn** [comment]
Using nvidia-docker and offical image nvidia/opencl:devel-ubuntu18.04
python version is 3.8.5 (stock ubuntu build)
success by modifing Run.py line41 to
```python
passphrase+=chr(int(pword[0]))
```

**Comment by famugong** [comment]
> This problem seems to be an issue of python version. The code works for python 3.7, and other version is not supported. To make the code work for other version of python, please use the search engine and python document to seek for help. You can paste your solution here so that other developers will benefit from it.

Thank you. I just ran the script using Python 3.7. My backup is a bit old so it didn't find the right password. From Zhihu [https://www.zhihu.com/question/20443317/answer/1127118621] they say this project needs modification for WeChat 7.0+, which has adopted different header. It didn't work for me but like I said my copy was from way back. I post it here so it may be of help.

**Comment by famugong** [comment]
> Using nvidia-docker and offical image nvidia/opencl:devel-ubuntu18.04
> python version is 3.8.5 (stock ubuntu build)
> success by modifing Run.py line41 to
> 
> ```python
> passphrase+=chr(int(pword[0]))
> ```

Thank you for sharing

**Comment by famugong** [comment]
/Lib/pbkdf2-sha1_aes-256-cbc.cl

change line 752 to:

if(((uint)(data[5] ^ iv[5])==0x40) && ((uint)(data[6] ^ iv[6])==0x20) && ((uint)(data[7] ^ iv[7])==0x20))

**Comment by whiteblackitty** [comment]
> /Lib/pbkdf2-sha1_aes-256-cbc.cl
> 
> change line 752 to:
> 
> if(((uint)(data[5] ^ iv[5])==0x40) && ((uint)(data[6] ^ iv[6])==0x20) && ((uint)(data[7] ^ iv[7])==0x20))

Your reply is out of the topic of this issue. What's more, I don't think this repo is designed specially for ANY software, but only SQLCipher standard. I must say that any issue or pull request which targets on unofficial variation of SQLCipher would not be encouraged and may be closed/deleted.
